name: PR QA

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Checkout and Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11, 16, 17]

    steps:
      - uses: actions/checkout@v2

      - name: JDK setup
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

  docker_test:
    name: Test Docker image
    needs: [ build ]
    uses: veraPDF/veraPDF-rest/.github/workflows/test-dkr-build.yml@gh-actions
    with:
      gh_checkout: ${{ github.head_ref }}

  purge-image:
    name: Delete image from ghcr.io
    needs: [ docker_test ]
    runs-on: ubuntu-latest
    steps:
      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.0.0
        with:
          # NOTE: at now only orgs is supported
          owner: veraPDF
          name: veraPDF-rest
          # NOTE: using Personal Access Token
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.head_ref }}