name: Test Docker deployment

on:
  workflow_call

jobs:
  test:
    name: Deploy and test image
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      verarest:
        image: ghcr.io/verapdf/verapdf-rest:pr-${{ github.event.pull_request.number }}
        ports:
          - 80:8080
    steps:
      - name: Test Profiles endpoint
        uses: wei/wget@v1
        with:
          args: -qO- 0.0.0.0/api/profiles
      - name: Test 1B profile endpoint
        uses: wei/wget@v1
        with:
          args: -qO- 0.0.0.0/api/profiles/1b
