name: PR QA

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Checkout and Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11, 16, 17]

    steps:
      - uses: actions/checkout@v2

      - name: JDK setup
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

  docker_test:
    name: Test Docker image
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: call-docker-image-build
        uses: "veraPDF/veraPDF-rest/.github/workflows/test-dkr-build.yml@gh-actions"
        with:
          files: core/target/site/jacoco/jacoco.xml
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
