name: PR QA

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Checkout and Build
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        java-version: [8, 11, 16, 17]

    steps:
      - uses: actions/checkout@v2
      - name: JDK setup
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Package with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Run REST server
        run: java -jar target/verapdf-rest-0.1.0-SNAPSHOT.jar server  </dev/null &>/dev/null &
      - name: Test API endpoint
        uses: wei/wget@v1
        with:
          args: -qO- http://localhost:8080/api
      - name: Test Profiles endpoint
        uses: wei/wget@v1
        with:
          args: -qO- http://localhost:8080/api/profiles
      - name: Test 1B profile endpoint
        uses: wei/wget@v1
        with:
          args: -qO- http://localhost:8080/api/profiles/1b
      - name: Kill rest server
        run: fuser -k 8080/tcp
