name: Test Docker deployment

on:
  workflow_call

jobs:
  test:
    name: Deploy and test image
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      verarest:
        image: ghcr.io/verapdf/verapdf-rest:pr-${{ github.event.pull_request.number }}
        ports:
          - 80:8080
    steps:
      - name: Install wget 
        run: apt-get update; apt-get install wget -y
      - name: Test Profiles endpoint
        run: wget -qO- verarest/api/profiles
      - name: Test 1B profile endpoint
        run: wget -qO- verarest/api/profiles/1b
